# Generated by Django 4.2.1 on 2023-06-05 13:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orkun', '0002_project_project_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
